import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'

import Button from '../components/Button'
import GitHub from '../components/Icons/GitHub'

import useUser, { STATES } from '../hooks/useUser'
import { loginWithGithub } from '../firebase/client'

import styles from './styles.module.css'

const Home = () => {
  const user = useUser()
  const router = useRouter()

  useEffect(() => {
    user && router.replace('/home')
  }, [user])

  const handleClick = () => {
    loginWithGithub().catch((err) => {
      console.error(err)
    })
  }
  return <>
    <Head>
      <title>twetdev | El twet para los desarrolladores</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/logo-dev.png' />
    </Head>

    <section className={styles.section}>
      <img className={styles.image} src='/logo-dev.png' alt='logo' />
      <h1 className={styles.title}>twetdev</h1>
      <h2 className={styles.subTitle}>
        Comparte y habla de desarrollo <br /> con otros desarrolladores 💻
      </h2>
      <div className={styles.content}>
        {user === STATES.NOT_LOGGED && (
          <Button onClick={handleClick}>
            <GitHub fill='#fff' width={24} height={24} />
            Iniciar sesión con Github
          </Button>
        )}
        {user === STATES.NOT_KNOWN && <img src='/spinner.gif' />}
      </div>
    </section>
  </>
}

export default Home