import Head from 'next/head'
import Link from 'next/link'
// Link se usa como un sistema de rutas sin necesidad de recargar la página
import { useRouter } from 'next/router'

const Home = () => {
  const router = useRouter()
  return (
    <div>
      <Head>
        <title>twetdev | El twet para los desarrolladores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type= "image/x-icon" href="https://cdn-icons-png.flaticon.com/512/4661/4661472.png" />
      </Head>
        
      <main>
        <h1>twetdev</h1>
          <nav>
            <Link href='/timeline'>timeline</Link>
          </nav>
      </main>
      <style jsx>{`

        h1 {
          text-align: center;
        }
        nav {
          font-size: 43px;
          text-align: center;
        }
      `}</style>
    </div>
  )
}

export default Home